### ISSUE TITLE
Agregar manejo conexión Internet

### ISSUE THREAD

**Issue by ppiova** [Emplea-do/MobileApp-Xamarin#31]
Agregar manejo conexión Internet

Referencia para posible utilización Nuget: Xam.Plugin.Connectivity

https://www.nuget.org/packages/Xam.Plugin.Connectivity

**Comment by Char0394** [comment]
No uses Xam.Plugin.Connectivity, usa Xamarin.Essentials mejor
https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?tabs=android

**Comment by sact1909** [comment]
Ey, Charleen, gracias por el feedback, si, este issue ya había sido trabajado, de me había olvidado cerrarlo, pero usé Xamarin.Essentials en vez del otro nuget... 

Aquí te attacho la imagen y gracias por el feedback, cualquier otro, súper bienvenido :D

![image](https://user-images.githubusercontent.com/23615129/82515355-04171a80-9ae6-11ea-9445-ec765fd73d60.png)

**Comment by sact1909** [comment]
I guess this issue is done, I'm closing it

![image](https://user-images.githubusercontent.com/23615129/99896175-02c4d700-2c5c-11eb-9ff5-82c2a394adb3.png)
