### ISSUE TITLE
Crear pantalla de lista de trabajo del app - Xamarin

### ISSUE THREAD

**Issue by umartinez22** [Emplea-do/MobileApp-Xamarin#5]
Como Software Developer crear la pantalla de busqueda donde estaran la lista de empleos disponibles.

Criterio de aceptación:

- Mostrar la cantidad de los empleos disponibles segun la busqueda.

**Crear el UI para cada elemento, este debe:**
- Mostrar el titulo del empleo.
- Mostrar si el empleo es remoto o in-site.
- Mostrar el nombre de la empresa.
- Mostrar el logo de la empresa.
- Mostrar la categoria del empleo.
- Mostrar la localización de la empresa.

**Comment by sact1909** [comment]
Done
