### ISSUE TITLE
Crear pantalla de detalle de trabajo - Xamarin

### ISSUE THREAD

**Issue by umartinez22** [Emplea-do/MobileApp-Xamarin#6]
Como Software Developer crear la pantalla de detalles del trabajo.

Criterio de aceptación:

- Mostrar el titulo del empleo.
- Mostrar si el empleo es remoto o in-site.
- Mostrar el nombre de la empresa.
- Mostrar el logo de la empresa.
- Mostrar la categoria del empleo.
- Mostrar la localización de la empresa.
- Mostrar la descripción del trabajo.
- Poder marcar como favorito el empleo (Solo se mostrara el icono, por ahora no hay insumo suficiente para realizar esta operación).

**Comment by sact1909** [comment]
@umartinez22 verificando este Issue, el ultimo punto, de agregar el botón de favorito (Heart ♥), solo se estará poniendo para hacer decoración de la pantalla, recordar, que el API hasta el momento solo es un GET y aunque se pueda realizar un "evento falso" no servirá de nada, ya que se necesita hacer un POST para capturar el Like del Job que se esta consultando, le indique a @AdrianaMota que solamente lo ponga para completar el UI, pero sin ningún afecto adjunto...

**Comment by umartinez22** [comment]
@sact1909 Gracias por informarlo, modifique el issue indicando que solo se mostrara por ahora el icono de favorito.
