### ISSUE TITLE
Crear pantalla de busqueda - Xamarin

### ISSUE THREAD

**Issue by umartinez22** [Emplea-do/MobileApp-Xamarin#7]
Como Software Developer crear la pantalla de busqueda mediante el cual el usuario podra buscar empleos segun su necesidad.

Criterio de aceptación:

- Mostrar un input por donde se podra buscar por keywords.
- Mostrar una lista de categoria por la que se podra filtrar la busqueda.
- Mostrar un input que indique que solo se buscaran los trabajos remotos.
- Mostrar un boton para realizar la busqueda.

**Comment by ppiova** [comment]
Issue done. With help of Claudio.
